var setupHelpers = require('./helperFunctions.js');

exports.description = 'Introduction to my interactive résumé application.';

exports.invoke = function (options, shell) {
    shell.setPassive('resume');
    setupHelpers(shell);
    shell.clearDisplay();
    shell.type("I bet you thought my resume was going to be dry and boring like everyone else's huh?");
    shell.type("Well I showed you!");
    shell.type("It's actually super modern and cutting edge.");
    shell.type("I mean, you can't get much more cutting edge than a terminal.");
    shell.type("Okay, so you probably want to see my résumé now. Give me a second to go fetch it...");
    shell.log();
    shell.type("Communicating with server...", 0, 0, 500);
    shell.type("...done!", 0, 0, 1000);
    shell.type("Spinning up tape drive...", 0, 0, 500);
    shell.type("...", 0, 0, 500);
    shell.type("...", 0, 0, 500);
    shell.type('...file corrupt!', 0, 0, 1500);
    shell.type("Accessing backups (A:)..........no disk", 0, 0, 500);
    shell.type('Accessing telegraph array...', 0, 0, 500);
    shell.type("we get signal");
    shell.type(".... --- .-- / .- .-. . / -.-- --- ..- / --. . -. - .-.. . -- . -.", 0, 0, 300);
    shell.type(".- .-.. .-.. / -.-- --- ..- .-. / -... .- ... . / .- .-. . / -... . .-.. --- -. --. / - --- / ..- ...", 0, 0, 300);
    shell.type("-.-- --- ..- / .- .-. . / --- -. / -.-- --- ..- .-. / .-- .- -.-- / - --- / -.. . ... - .-. ..- -.-. - .. --- -.", 0, 0, 1000);
    shell.type("what you say?");
    shell.type("-.-- --- ..- / .... .- ...- . / -. --- / -.-. .... .- -. -.-. . / - --- / ... ..- .-. ...- .. ...- . / -- .- -.- . / -.-- --- ..- .-. / - .. -- .", 0, 0, 1000);
    shell.type("Okay well the telegraph was a fail I guess. Any other ideas?");
    shell.log();
    shell.type("You know, I'm actually surprised you even need to see my résumé...");
    shell.type("I'm kind of a big deal.");
    shell.type("You should probably just hire me.");
    shell.type("You know it's the right thing to do. Your company needs me.");
    shell.type("But just in case you are still uncertain...");
    shell.log('<div style="height: 400px;"><img style="height:400px;" src="/images/hypnotoad.gif" /></div>', { dontType: true });
    shell.type("You couldn't possibly resist the influence of hypnotoad.", 35, 0, 5000);
    shell.type("Still not convinced?");
    shell.type("Okay okay.....have a look at my résumé.", 35, 0, 2000);
    shell.log();
    shell.execute('help');
};